### ISSUE TITLE
[landscape] Discussion of Storage Types

### ISSUE THREAD

**Issue by gh-Devin** [nextarch/toc#38]
Suggested storage types should cover databases, distributed storage.
Database
-Caching databases
-relational databases
-non-relational databases
....
Distributed Storage
-File storage
-Block storage
-Object Storage
-Edge Storage
-Storage Data Management
...

**Comment by bartdong** [comment]
I think it's hard to tell whether database should combine with storage.
In my opinion, database always has a relationship with data analysis.
If we focus on the best practice, shall we just set one SIG-DataAnalysis to cover them all?
Plus offline analysis, real-time analysis, HTAP...
