### ISSUE TITLE
Vote for TOC Meeting Plan 

### ISSUE THREAD

**Issue by caoqianyun** [nextarch/toc#44]
We plan to hold the NextArch TOC Meeting every two weeks and hope all TOC members can attend in time. 

To select a suitable meeting time for most of you, every TOC member could submit a commit to select **(a)** or **(b)** as follows：

- (a) Every other Thursday at 05 pm Pacific Time / 9 am UTC+8 Beijing Time.
- (b) Every other Tuesday at 05 pm Pacific Time / 9 am UTC+8 Beijing Time.

The vote will open from today to 11 pm UTC+8 Beijing Time, January 13, 2022 / 7 am Pacific Time, January 13, 2022.

**Comment by gh-Devin** [comment]
I choose A 
: )

**Comment by qianzhangxa** [comment]
B looks good to me 😄

**Comment by fanweixiao** [comment]
🎉  for Option A
🚀  for Option B

**Comment by exexute** [comment]
I choose A
: )

**Comment by ustcchensu** [comment]
a

**Comment by ruilibuaa** [comment]
choose A

**Comment by bluejoe2008** [comment]
I choose A
: )

**Comment by WangJP2k** [comment]
Both Okay ;-)

**Comment by qinannmj** [comment]
I choose A.

**Comment by yangwenmai** [comment]
I choose A

**Comment by Meiye-lj** [comment]
I choose A

**Comment by lhgao** [comment]
A

**Comment by stingfeng** [comment]
a

**Comment by lhgao** [comment]
谢谢，来信已收到！

**Comment by caoqianyun** [comment]
According to the principle of fifty percent majority vote, TOC meeting will be held in every other Thursday at 05 pm Pacific Time / 9 am UTC+8 Beijing Time. 

Thank you all!
